
input:
  # MRI | static
  # image_type: MRI
  image_type: static
  # data_path: data\phase2
  data_path: data\static\BrainProtonDensitySlice.png

output:
  plot:
    alpha: 0.75
  mask_path: output\BrainProtonDensity\BrainProtonDensitySliceOutput.png
  mha_path: output\BrainProtonDensity\BrainProtonDensitySliceOutput.mha

smoothing:
  timestep: 0.125 # 0.125 for 2D, 0.0625 for 3D
  n_iters: 9
  conductance_param: 10

gradient_magnitude:
  sigma: 1.0

sigmoid:
  min: 0.0
  max: 1.0
  alpha: -0.5
  beta: 3.0

fastmarching:
  stopping_time: 100
  list_seed:
    - [81, 114, 0]
    - [100, 114, 0]

binarizer:
  lower_threshold: 0
  upper_threshold: 100000
  inside_value: 0
  outside_value: 1

gac:
  propagation_scaling: 0.5
  curvature_scaling: 1.0
  advection_scaling: 0.5
  max_rmse: 0.01
  n_iters: 50