
input:
  # MRI | static
  image_type: MRI
  # image_type: static
  data_path: data\phase2
  # data_path: data\static\abdominal_2d.png

output:
  plot:
    alpha: 0.6
  mask_path: output\abdominal_2d\abdominal_2d_output.png
  mha_path: output\abdominal_2d\abdominal_2d_output.mha

3D:
  view_idx: 20

smoothing:
  timestep: 0.0625 # 0.125 for 2D, 0.0625 for 3D
  n_iters: 5
  conductance_param: 10

gradient_magnitude:
  sigma: 0.5

sigmoid:
  min: 0.0
  max: 10.0
  alpha: -5
  beta: 15

fastmarching:
  stopping_time: 10
  list_seed:
    - [112, 136, 13]
    - [122, 135, 13]
    - [123, 135, 13]
    - [216, 161, 25]
    - [215, 154, 25]
    - [215, 164, 25]
    - [103, 150, 11]
    - [215, 161, 11]
    - [106, 153, 5]
    - [111, 144, 2]
    - [199, 158, 28]
    - [199, 158, 30]
    - [126, 155, 21]
    - [129, 147, 21]
    - [102, 160, 16]
    - [114, 165, 19]

binarizer:
  lower_threshold: 1
  upper_threshold: 1000
  inside_value: 0
  outside_value: 1

gac:
  propagation_scaling: 0.5
  curvature_scaling: 1.0
  advection_scaling: 0.5
  max_rmse: 0.01
  n_iters: 50